### ISSUE TITLE
Could we please have the option to reboot instead of just logout at the end?

### ISSUE THREAD

**Issue by jby** [jamf/DEPNotify-Starter#15]
As stated in the subject line: Could we have the option to reboot at the end instead of just a logout?

**Comment by kbareis** [comment]
@jby, I'll take a look and see how easy it could be to implement. Any thoughts on how you would like it to be configured? At this point, the script is automatically making the decision to logout vs quit at the presence of FileVault configuration. As I type, it sounds like I am going to have to make some sort of decision tree. Like, if FileVault on, then reboot. If FileVault is not detected, then quit, unless admin states reboot. 

Would there be need for a shutdown command as well?

**Comment by jby** [comment]
No, I don't think so - and since reboot starts with a logout, I _think_ that it will trigger FV enablement as well...

**Comment by MatGriffin** [comment]
Hello, did this get implemented as the script is pretty awesome just at the end we need to the user to reboot as we install things like DisplayLink which require a reboot.

So or process would be at the end of DEP Notify user clicks Restart button, enters FileVault password and Mac reboots.

**Comment by MatGriffin** [comment]
i got it

ContinueButtonRestart

**Comment by ekrizon** [comment]
> ContinueButtonRestart

Can you elaborate how you did this? I want to reboot after completion.

**Comment by mglover3145** [comment]
> Can you elaborate how you did this? I want to reboot after completion.

Visit this link: https://gitlab.com/Mactroll/DEPNotify#advanced-workflows

Scroll down to the "Completion" section and it has commands you can use to restart. You'll edit the script to use one of these commands.

**Comment by jby** [comment]
> > Can you elaborate how you did this? I want to reboot after completion.
> 
> Visit this link: https://gitlab.com/Mactroll/DEPNotify#advanced-workflows
> 
> Scroll down to the "Completion" section and it has commands you can use to restart. You'll edit the script to use one of these commands.

Actually here: https://gitlab.com/Mactroll/DEPNotify#continuebuttonrestart

**Comment by jby** [comment]
The above works just fine
