### ISSUE TITLE
Text Fields and popus at registration not appearing..

### ISSUE THREAD

**Issue by kerouak** [jamf/DEPNotify-Starter#17]
**Describe the bug**
When I configure the text and popups to appear at Registration "true" The window appears and "register this mac" button ok. However, the text and popup fields are not showing, only a clear white box.
I click register and it runs through stating that no entries have been made for computer name, department , building etc.
Attached screenshot of splash window

**To Reproduce**

**Expected behavior**

**Screenshots**

**Logs**
Please attach the following logs:
- /var/tmp/depnotify.log
- /var/tmp/depNotifyDebug.log
- /var/log/jamf.log

**Software Versions (please complete the following information):**
 - macOS Version 10.13
- Jamf Version 10.10
- DEP Notify Version 1.1.0

**Additional context**

**Comment by kbareis** [comment]
Hey @kerouak, what version of DEPNotify and DEPNotify script are you using? From your note above, I would guess that you are using versions that are incompatible with each other. Please check out https://github.com/jamf/DEPNotify-Starter/blob/master/RELEASES.md for recommendations of script / app pairings.

**Comment by kbareis** [comment]
Hey @kerouak, I am going to close this issue. If you are still experiencing issues, please re-open. 

Thanks, Kyle
