### ISSUE TITLE
DEPNotify has stopped working

### ISSUE THREAD

**Issue by jby** [jamf/DEPNotify-Starter#31]
**Describe the bug**
When logging in to a newly enrolled MacBook Pro, DEPNotify no longer starts as expected. When trying to start manually I get the following:

```
'Script result: FSPathMakeRef(/Applications/Utilities/DEPNotify.app) failed with error -43.'
```

I have also logged a support case at JamfNation about this: JAMF-0836154

**To Reproduce**
Freshly install 10.15.1, log in with admin user, nothing happens.

**Expected behavior**
I expect DEPNotify to start and start running it's script to install my other policies.

**Screenshots**

**Logs**
Please attach the following logs:
```
sudo jamf policy -event depnotify
Password:
Checking for policies triggered by "depnotify" for user "toadmin"...
Executing Policy 02 Install DEPNotify
Downloading CME_logos.pkg...
Downloading https://euc1-jcds.services.jamfcloud.com//download/31b7f1de8e854985af9094f0e8ce0e51/CME_logos.pkg?token=33ce7612723346ddae4650ea7a59fdcbqe1tfzf4e5l4d4ul06h6qlcm8msd1p13...
Verifying package integrity...
Installing CME_logos.pkg...
Successfully installed CME_logos.pkg.
Running script Install & Run DEPNotify...
Script exit code: 1
Script result: FSPathMakeRef(/Applications/Utilities/DEPNotify.app) failed with error -43.

Error running script: return code was 1.
```
**Software Versions (please complete the following information):**
 - macOS Version: 10.15.1
- Jamf Version: 10.17.1 (today, but same with 10.16.whatever it was before upgrade this past weekend)
- DEP Notify Version: 2.0.0

**Additional context**

**Comment by dpass883** [comment]
Noticed that the DEPNotify app is not in the Utilities folder.  Must be what's causing the error as the file the script is looking for isn't there.  I'm using the PreStage .pkg installation to place it there.  Logs on the Jamf side show that this ran.  Unsure if it is Jamf or the DEPNotify installer at this point.

**Comment by jby** [comment]
I had a colleague that had cleaned out too many pkgs from our Jamf server, the DEPNotify.pkg was actually not being installed anymore... :blush:
