### ISSUE TITLE
Tabbing doesn't work as intended

### ISSUE THREAD

**Issue by stephen-bailey-carta** [jamf/DEPNotify-Starter#40]
**Describe the bug**
I'm using the default example in the script of Computer name, asset tag, home office and department. However, hitting the tab key only goes back and forth between computer name and asset tag, instead of tabbing through all 4 fields and the continue button. 

**To Reproduce**
1. Go to 'First popup page with text input'
2. Click on 'Computer Name'
3. Hit tab a few times to see it bounces back and forth between two instead of cycling through the text boxes and drop downs

**Expected behavior**
I was expecting to be able to tab through all options as well as the continue button.
**Screenshots**

**Logs**
Please attach the following logs:
[jamf.log](https://github.com/jamf/DEPNotify-Starter/files/6072240/jamf.log)
[depnotifyDebug.log](https://github.com/jamf/DEPNotify-Starter/files/6072237/depnotifyDebug.log)
[depnotify_old.log](https://github.com/jamf/DEPNotify-Starter/files/6072238/depnotify_old.log)

**Software Versions (please complete the following information):**
 - macOS Version 11.2.1 and 10.15.7
- Jamf Version 10.25
- DEP Notify Version 1.1.6

**Additional context**

**Comment by BIG-RAT** [comment]
Thanks for the details, this however is an issue with the app rather than the setup script.  I'd suggesting opennig an issue here: https://gitlab.com/Mactroll/DEPNotify/-/issues
